image: gitlab-registry.glispa.com/java/maven-builder

stages:
  - test
  - deploy
  - release

Test:
  services:
    - name: johnnypark/kafka-zookeeper:1.0.0
      alias: kafka
    - name: influxdb:1.3.9-alpine
      alias: influxdb
  variables:
    # InfluxDB vars
    INFLUXDB_HTTP_AUTH_ENABLED: "true"
    INFLUXDB_DB: "dbname"
    INFLUXDB_ADMIN_USER: "admin"
    INFLUXDB_ADMIN_PASSWORD: "apassword"
    INFLUXDB_USER: "user"
    INFLUXDB_USER_PASSWORD: "upassword"

  stage: test
  script:
    - mvn -B -U clean test -Dkafka.host=kafka -Dinfluxdb.host=influxdb
  except:
    - tags

Deploy Snapshot:
  stage: deploy
  script:
    - mvn -B -U clean deploy -DskipTests
  only:
    - master

Release:
  when: manual
  variables:
    GIT_STRATEGY: clone
  stage: release
  script:
    - git checkout -B "$CI_BUILD_REF_NAME"
    - mvn -B release:clean release:prepare release:perform -Darguments="-DskipTests"
  only:
    - master
  except:
    - tags
